### ISSUE TITLE
Shape errors when calling a converted `tf.Module`

### ISSUE THREAD

**Issue by romanngg** [deepmind/tf2jax#37]
Here's a Colab example where I copied the TF Module sample code from https://www.tensorflow.org/api_docs/python/tf/Module
https://colab.research.google.com/gist/romanngg/4157eb94d0e1a47f8d300738cbfe9270/tf2jax_module_fail.ipynb

Calling the module works, as well as the associated `tf.function`, but after conversion the JAX there is a dimension mismatch. I didn't have any of such issues with `tf.keras.Model`s. Thanks again for the great library!

**Comment by shaobohou** [comment]
Thanks for the bug report! 

This is was very valuable and should be fixed #40
